#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
  path: /api/login_check

register:
  path: /api/register
  controller: App\Controller\RegistrationController::index
  methods: POST

confirm:
  path: /api/confirm
  controller: App\Controller\RegistrationController::confirmRegistration
  methods: GET

admin_check:
  path: /api/admin_check
  controller: App\Controller\AdminController::index
  methods: GET
