#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
  path: /api/login_check

register:
  path: /api/register
  controller: App\Controller\RegistrationController::index
  methods: POST

confirm:
  path: /api/confirm
  controller: App\Controller\RegistrationController::confirmRegistration
  methods: GET

admin_check:
  path: /api/self
  controller: App\Controller\UserController::index
  methods: GET

stickers:
  path: /api/stickers
  controller: App\Controller\StickerController::getAll
  methods: GET

add_sticker:
  path: /api/sticker
  controller: App\Controller\StickerController::add
  methods: POST

update_sticker:
  path: /api/sticker-update
  controller: App\Controller\StickerController::update
  methods: POST
