#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
  path: /api/login_check

register:
  path: /api/register
  controller: App\Controller\RegistrationController::index
  methods: POST

confirm:
  path: /api/confirm
  controller: App\Controller\RegistrationController::confirmRegistration
  methods: GET

login:
  path: /api/login
  controller: App\Controller\RegisterController::confirmRegistration
  methods: POST
