api_login_check:
  path: /api/login_check

register:
  path: /{_locale}/api/register
  controller: App\Controller\RegistrationController::index
  methods: POST

confirm:
  path: /{_locale}/api/confirm
  controller: App\Controller\RegistrationController::confirmRegistration
  methods: GET

self:
  path: /api/self
  controller: App\Controller\UserController::index
  methods: GET

stickers:
  path: /api/stickers
  controller: App\Controller\StickerController::getAll
  methods: GET

add_sticker:
  path: /{_locale}/api/sticker/add
  controller: App\Controller\StickerController::add
  methods: POST

update_sticker:
  path: /{_locale}/api/sticker/update
  controller: App\Controller\StickerController::update
  methods: POST

give_sticker:
  path: /{_locale}/api/sticker/give
  controller: App\Controller\StickerController::giveStickerToUser
  methods: GET

get_user_items:
  path: /{_locale}/api/user/{id}/items
  controller: App\Controller\InventoryItemController::getUserItems
  methods: GET

get_user_info:
  path: /{_locale}/api/user/{id}
  controller: App\Controller\UserController::getUserInfo
  methods: GET

sell_item:
  path: /{_locale}/api/item/sell/{id}
  controller: App\Controller\InventoryItemController::sellItem
  methods: POST

get_offers:
  path: /{_locale}/api/offers
  controller: App\Controller\OfferController::getOffers
  methods: GET

create_offer:
  path: /{_locale}/api/offer/create
  controller: App\Controller\OfferController::createOffer
  methods: POST

remove_offer:
  path: /{_locale}/api/offer/remove/{id}
  controller: App\Controller\OfferController::removeOffer
  methods: DELETE

accept_offer:
  path: /{_locale}/api/offer/accept/{id}
  controller: App\Controller\OfferController::acceptOffer
  methods: POST

get_user_offers:
  path: /{_locale}/api/user/{id}/offers
  controller: App\Controller\OfferController::getUserOffers
  methods: GET
